version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: task-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P StrongPassword123! -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: task-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo:7
    container_name: audit-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  audit-api:
    build: D:\DotNetProjects\AuditApi\AuditApi
    container_name: audit-api
    ports:
      - "5080:8080"
    environment:
      - Mongo__ConnectionString=mongodb://mongodb:27017
      - Mongo__Database=AuditDb
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb

  task-api:
    build: .
    container_name: task-api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True;
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
      - RABBITMQ__QUEUENAME=activities
      - DOTNET_ENVIRONMENT=Development
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started

volumes:
  sql_data:
  mongo_data: