services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: task-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -Q 'SELECT 1' -C || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: task-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongodb:
    image: mongo:7
    container_name: audit-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  audit-api:
    build: C:\Users\LENOVO\RiderProjects\AuditApi\AuditApi
    container_name: audit-api
    ports:
    - "5080:8080"
    environment:
    - MongoDb__ConnectionString=${MONGO_CONNECTION_STRING}
    - MongoDb__DatabaseName=${MONGO_DATABASE}
    - RabbitMQ__HostName=${RABBITMQ_HOST}
    - RabbitMQ__Port=${RABBITMQ_PORT}
    - RabbitMQ__UserName=${RABBITMQ_USERNAME}
    - RabbitMQ__Password=${RABBITMQ_PASSWORD}
    - RabbitMQ__QueueName=${RABBITMQ_QUEUE}
    - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      mongodb:
       condition: service_healthy
      rabbitmq:
        condition: service_healthy


  task-api:
    build: .
    container_name: task-api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_SERVER};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
      - RabbitMQ__HostName=${RABBITMQ_HOST}
      - RabbitMQ__Port=${RABBITMQ_PORT}
      - RabbitMQ__UserName=${RABBITMQ_USERNAME}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
      - RabbitMQ__QueueName=${RABBITMQ_QUEUE}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Stripe__SecretKey=${STRIPE_SECRET_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
      - JWT__signingKey=${JWT_SIGNING_KEY}
      - AuditApi__BaseUrl=${AUDIT_API_BASE_URL}
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  sql_data:
  mongo_data:
  rabbitmq_data: